//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTX_News.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MB_MtxNews
    {
        public int MtN_ID { get; set; }
        public int MtN_TwrNumer { get; set; }
        public string MtN_TwrKod { get; set; }
        public string MtN_Komentarz { get; set; }
        public System.DateTime MtN_TiStamp { get; set; }
        public System.DateTime MtN_DataDo { get; set; }
        public short MtN_IloscDni { get; set; }
        public byte MtN_Stan { get; set; }
        public string MtN_TwrNazwa { get; set; }
        public string MtN_KtoWprowadzil { get; set; }
        public string MtN_Producent { get; set; }
    }
}
